#!/bin/bash
CVC5_REPO=/home/panda/git/cvc5
echo "**** Compile ethos"
./configure.sh debug
cd build
make -j4

echo "**** Run ethos + desugar"
./src/ethos --plugin.desugar-vc $CVC5_REPO/proofs/eo/cpc/Cpc.eo
echo "**** Verify that it parses"
./src/ethos ../plugins/desugar/eo_desugar_vcs.eo

echo "**** Generate SMT2"
./src/ethos --plugin.smt-meta ../plugins/smt_meta/eo_model.eo
echo "**** Verify that it parses"
cvc5 ../plugins/smt_meta/smt_meta_gen.smt2
cd ..
